dist: trusty
language: cpp

cache:
  ccache: true

os:
  - linux

compiler:
  - gcc
  - clang
  
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential freeglut3-dev