sudo: required

dist: trusty
language: cpp

cache:
  ccache: true

os:
  - linux

compiler:
  - gcc
  - clang
  
 addons:
  apt:
    packages:
      - build-essential
      - freeglut3-dev
  
  before_script:
  # Prepare build directory
  - mkdir -p build
  
  
  script:
  # Build BTpp
  - (cd build; cmake .. ;cmake --build . )
